apiVersion: apps/v1
kind: Deployment
metadata:
  name: medclinical
  labels:
    app: medclinical

spec:
  replicas: 3
  selector:
    matchLabels:
      app: medclinical
  template:
    metadata:
      labels:
        app: medclinical

    spec:
      containers:
      - name: medclinical-api
        image: leonardosartorello/vollmed:v8
        ports:
        - containerPort: 3000

        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: dados-medclinical 
              key: DB_HOST

        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: dados-medclinical     
              key: DB_DATABASE

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-medclinical
              key: DB_PASSWORD
