apiVersion: v1
kind: Service
metadata:
  name: nodeport-api
spec:
  type: NodePort
  selector:
    app: deploy-medclinical
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30007

---

apiVersion: apps/v1
kind: Service
metadata:
  name: mysql
  labels: mysql

spec:
  ports:
  - port: 3306
    name: mysql
  ClusterIP: None
  selector:
    app: pod-mysql